### ISSUE TITLE
Fuzzy searching not working for books

### ISSUE THREAD

**Issue by josh-byster** [hack4impact-uiuc/philareads#102]
Not sure if this is a known bug but the searching isn't functioning as expected—searching "hu" for example should turn up "Huckleberry Finn" but instead shows nothing. But searching for "h" works. 
<img width="517" alt="screen shot 2018-11-09 at 1 02 37 am" src="https://user-images.githubusercontent.com/8664074/48248051-66547280-e3bb-11e8-859c-353ad5f3c24d.png">
<img width="432" alt="screen shot 2018-11-09 at 1 02 34 am" src="https://user-images.githubusercontent.com/8664074/48248052-66547280-e3bb-11e8-9285-13d578a4a934.png">

**Comment by Davidw1339** [comment]
Thanks for adding this, the problem is just because of case sensitivity. 'h' occurs in 'The' but 'hu' never occurs in the book title. Once we fix the casing on the substring search this will work as expected

**Comment by Davidw1339** [comment]
For now when you're searching just pay attention to case
