### ISSUE TITLE
Parse CSV into Book model

### ISSUE THREAD

**Issue by micleo2** [hack4impact-uiuc/philareads#119]
**Describe the solution you'd like**
A BE endpoint that will support parsing a CSV file and creating a Book model in the backend.

**Comment by XuanLi-Leong** [comment]
Sample of CSV columns

### Book
![image](https://user-images.githubusercontent.com/20269588/48389861-e97c0e00-e6c4-11e8-9d73-710df59b745a.png)

### Quiz
![image](https://user-images.githubusercontent.com/20269588/48389876-f4cf3980-e6c4-11e8-8767-c26127bf0f0e.png)
