### ISSUE TITLE
Profile: Create badge images

### ISSUE THREAD

**Issue by XuanLi-Leong** [hack4impact-uiuc/philareads#127]
**Is your feature request related to a problem? Please describe.**
We need badge images

**Describe the solution you'd like**
- Number of quizzes (1, 5, 10, 20)
- Number of perfect scores  (1, 5, 10, 20)
- Number of books “read” (1, 5, 10, 20)
- *Let's postpone this*: Reading beyond your grade (only available to Middle school students) (1, 5)

**Comment by hungryflamingcat** [comment]
Finished the first draft of icons for # quizzes, # perfect scores, and # books read

<img width="623" alt="image" src="https://user-images.githubusercontent.com/13006066/48529975-414c7d80-e85b-11e8-98f0-bc70529ce3b6.png">

**Comment by Davidw1339** [comment]
Dang really great job! I really like how you did the book badges
It'd be cool if you could incorporate some more of the philareads colors 

![image](https://user-images.githubusercontent.com/9372512/48530150-17478b00-e85c-11e8-9353-d826ad5674a2.png)

but it might be hard so no worries. I'm quite satisfied with the current result

**Comment by hungryflamingcat** [comment]
update: tried to make the quiz icons more cohesive with the style of the book icon

<img width="738" alt="image" src="https://user-images.githubusercontent.com/13006066/48533738-3ef21f80-e86b-11e8-93ba-ea26224be021.png">

**Comment by XuanLi-Leong** [comment]
Thanks for the great work @hungryflamingcat  🎨
