### ISSUE TITLE
Profile: History page

### ISSUE THREAD

**Issue by XuanLi-Leong** [hack4impact-uiuc/philareads#130]
**Is your feature request related to a problem? Please describe.**
What does the profile history page look like?

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/20269588/48393508-7f1f9980-e6d5-11e8-9cbe-bbd59759fed2.png)

**Comment by XuanLi-Leong** [comment]
Maybe we should axe this page in concern of time, so tt we can build out admin features @Davidw1339

**Comment by Davidw1339** [comment]
> Maybe we should axe this page in concern of time, so tt we can build out admin features @Davidw1339

Sounds good to me i dont think its that necessary
