### ISSUE TITLE
FE: Book CSV/add/edit additional styling and integration with backend

### ISSUE THREAD

**Issue by josh-byster** [hack4impact-uiuc/philareads#158]
This issue will be closed when we have some CSS changes and testing with the backend to make sure the FE calls the API endpoints properly.

**Comment by XuanLi-Leong** [comment]
Some weird behavior I encountered (haven't investigated, if you know this isn't a bug pls mention):
- Editing a book creates a new book
- Editing a book *without changing the name* causes a "Book already exists" error

**Comment by Davidw1339** [comment]
> Some weird behavior I encountered (haven't investigated, if you know this isn't a bug pls mention):
> 
> * Editing a book creates a new book
> * Editing a book _without changing the name_ causes a "Book already exists" error
> 
> I'm guessing we might currently just be creating new book because edit endpoint may not exist or smt

Oh yea yea we need to update to use the new endpoints
