### ISSUE TITLE
Update description on GH repo & README.md

### ISSUE THREAD

**Issue by josh-byster** [hack4impact-uiuc/philareads#235]
**Describe the solution you'd like**

It would be awesome if we could have a short description of the project instead of the `now.sh` link, since if we want to showcase our work by pinning the repository on our on GitHub profiles, I think it'll be nice to give people a short description of what it does :)

**Comment by josh-byster** [comment]
Thanks David! :D Also it doesn't look like the SWEs have edit permissions to that so if you or @XuanLi-Leong wouldn't mind updating that, that'd be awesome!

**Comment by XuanLi-Leong** [comment]
Updated the description!

**Comment by micleo2** [comment]
Unexpected issue :+1:
