### ISSUE TITLE
Seed local database with mock data

### ISSUE THREAD

**Issue by dkh215** [hack4impact-uiuc/philareads#253]
When running the project for the first time, we should seed the local database with mock data.

**Comment by josh-byster** [comment]
@dkh215 Hello! I was one of the software developers for this project and I'm so glad/excited to see this project is being actively worked on and getting ready for deployment. 

To follow up on this issue, does `create_dummy_data.py` in the `backend` folder help at all with this?

**Comment by dkh215** [comment]
Hey @josh-byster!  Yes, super helpful 👌 we'll just need to incorporate this into a "Getting Started Guide" for folks that are setting up the project for the first time.

**Comment by tutordelphia** [comment]
I will be working on using the create_dummy_data.py to seed the database. I'll create a django dump from that and have a script that will run in docker that will seed the database with that data if none exists. I think I have an example for this in another project I'm working on that I can base this on.
