### ISSUE TITLE
Update Python packages to address security alerts

### ISSUE THREAD

**Issue by dkh215** [hack4impact-uiuc/philareads#269]
List of Alerts: https://github.com/hack4impact-uiuc/philareads/network/alerts

**Comment by tutordelphia** [comment]
Thanks, I'll update the packages and setup pyup to automatically check for additional updates. I'm a bit uncomfortable updating the libraries without a test suite to make sure there are no conflicts so I'll create a ticket for us to develop a manual series of tests until they can be automated.

**Comment by tutordelphia** [comment]
I'm going to hold off on PyUp until I can set up a cron job on our Linode instance (the job really can be run from any linux computer that is always on) so I'll work manually for now.
To address security issues, we'll need to change the following libraries:
```
requests: 2.18.4 > 2.22.0
SQLAlchemy 1.1.14 > 1.3.3
PyJWT 1.4.2 > 1.7.1
urllib3 1.22 > 1.25.2
```
I'll try those out first (after checking what changed between the versions and then will work on updating the rest of the packages.

**Comment by tutordelphia** [comment]
There are a lot of DeprecationWarning messages after trying these updates. The 6 backend tests pass but I'd like to address these messages in the ticket so future updates aren't blocked.

A DeprecationWarning occurs when running PyTest. Additional warnings occur after attempting to update packages.

**To Reproduce**
Steps to reproduce the behavior:
1. Install dev dependencies
2. Run `pytest` and view the warnings
3. Update libraries
 ```requests: 2.18.4 > 2.22.0
SQLAlchemy 1.1.14 > 1.3.3
PyJWT 1.4.2 > 1.7.1
urllib3 1.22 > 1.25.2
```
4. Run `pytest` again and view additional warnings

**Expected behavior**
No warnings

Sample of Warnings:
```
DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  formatvalue=lambda x: '=' + x)
```
```
/home/adam/.pyenv/versions/3.7.3/envs/philareads/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py:157: SADeprecationWarning: Use .persist_selectable
  info = getattr(mapper.mapped_table, 'info', {})
```
```
/home/adam/.pyenv/versions/3.7.3/envs/philareads/lib/python3.7/site-packages/jwt/api_jws.py:145: DeprecationWarning: It is strongly recommended that you pass in a value for the "algorithms" argument when calling decode(). This argument will be mandatory in a future version.
  DeprecationWarning
```

**Comment by tutordelphia** [comment]
It seems like I'm running into issues trying to update the packages with the security issues without updating the related packages at the same time (for example, `Flask-SQLAlchemy` was out of date compared with `SQLAlchemy`). I'm going to update additional libraries to keep them more in sync with each other. Eventually, I'll update everything but I try to be conservative so if there is an issue, I'll know where it is coming from.

**Comment by tutordelphia** [comment]
I forgot this project uses pipenv. I'll update the piplock file as well.
