### ISSUE TITLE
Bug: NavBar renders its component when the route matches?

### ISSUE THREAD

**Issue by XuanLi-Leong** [hack4impact-uiuc/philareads#28]
**Describe the bug**
@hungryflamingcat caught this when working on the parent advice page. The nav bar would render the Advice component, in addition to her own page component rendering the Advice component... something like that.

**Describe the solution**
Need to investigate. May not be an actual "bug".

- Check logic around where we're rendering the Page components, and that we're not rendering it twice
- Maybe move the nav bar to a parent component.

**Comment by josh-byster** [comment]
I saw this too on occasion, and it's not consistently triggering a render (i.e. sometimes it only renders the component once as it should), so I have a feeling that it's unintentional.

**Comment by XuanLi-Leong** [comment]
Think the issue was rendering `<Route.../>` components inside a component, instead of just `<PReadsNavBar/>`
