### ISSUE TITLE
BE authentication endpoints shouldn't read data from form

### ISSUE THREAD

**Issue by micleo2** [hack4impact-uiuc/philareads#37]
**Is your feature request related to a problem? Please describe.**
The BE currently uses data taken in from HTML form elements. However, it would be easier to test and for the FE if the implementation changed to read instead from regular application/json data.

**Describe the solution you'd like**
A changed implementation of both API endpoints /login and /register.

**Comment by Davidw1339** [comment]
Fixed with pull #38
