### ISSUE TITLE
FE: Create global navbar

### ISSUE THREAD

**Issue by XuanLi-Leong** [hack4impact-uiuc/philareads#59]
**Is your feature request related to a problem? Please describe.**
Now that our site no longer has a KIDS VERSION and PARENTS VERSION, we can have a *global* navbar.

**Describe the solution you'd like**
Global navbar! Extract the current navbar into a component

**Comment by josh-byster** [comment]
I am happy to do this as soon as we merge in the login PR, which I'm just finishing up validation for.
